inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

require:
  - rubocop-ast
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance
  - rubocop-factory_bot
