name: Run rspec

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [3.3]
        node: [20]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install Playwright and dependencies
      run: |
        npm install
        npx playwright install-deps
        npx playwright install

    - name: Prepare database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/app_test
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run RSpec and Capybara tests
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/app_test
      run: bundle exec rspec
